// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module design_1_v_tpg_0_0_tpgPatternCrossHatch (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        y,
        x,
        width,
        height,
        color,
        ap_return_0,
        ap_return_1,
        ap_return_2
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [15:0] y;
input  [15:0] x;
input  [15:0] width;
input  [15:0] height;
input  [7:0] color;
output  [7:0] ap_return_0;
output  [7:0] ap_return_1;
output  [7:0] ap_return_2;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
reg   [9:0] yCount_V_2;
reg   [0:0] vHatch;
reg   [9:0] xCount_V_2;
wire   [1:0] whiYuv_1_address0;
reg    whiYuv_1_ce0;
wire   [7:0] whiYuv_1_q0;
wire   [1:0] blkYuv_1_address0;
reg    blkYuv_1_ce0;
wire   [7:0] blkYuv_1_q0;
reg   [0:0] empty_reg_122;
wire   [0:0] icmp_ln1405_fu_248_p2;
reg   [0:0] icmp_ln1405_reg_539;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] trunc_ln1405_fu_254_p1;
reg   [0:0] trunc_ln1405_reg_543;
wire   [0:0] icmp_ln1405_1_fu_262_p2;
reg   [0:0] icmp_ln1405_1_reg_549;
reg   [0:0] icmp_ln1405_1_reg_549_pp0_iter1_reg;
wire   [0:0] and_ln1405_fu_280_p2;
reg   [0:0] and_ln1405_reg_553;
wire   [0:0] cmp57_fu_374_p2;
reg   [0:0] cmp57_reg_560;
reg   [0:0] cmp57_reg_560_pp0_iter1_reg;
wire   [0:0] cmp59_fu_380_p2;
reg   [0:0] cmp59_reg_566;
wire   [0:0] icmp_ln1429_fu_386_p2;
reg   [0:0] icmp_ln1429_reg_574;
reg   [0:0] icmp_ln1429_reg_574_pp0_iter1_reg;
wire   [7:0] conv_i10_fu_409_p3;
reg   [7:0] conv_i10_reg_578;
wire   [7:0] conv_i_fu_416_p3;
reg   [7:0] conv_i_reg_584;
wire   [0:0] icmp_ln1057_fu_427_p2;
reg   [0:0] icmp_ln1057_reg_590;
wire   [0:0] icmp_ln1049_1_fu_433_p2;
reg   [0:0] icmp_ln1049_1_reg_594;
reg   [0:0] ap_phi_mux_empty_phi_fu_126_p4;
wire   [9:0] grp_reg_ap_uint_10_s_fu_224_d;
wire   [9:0] grp_reg_ap_uint_10_s_fu_224_ap_return;
reg    grp_reg_ap_uint_10_s_fu_224_ap_ce;
wire    ap_block_state1_pp0_stage0_iter0_ignore_call10;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call10;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call10;
wire    ap_block_pp0_stage0_11001_ignoreCallOp14;
wire   [0:0] ap_phi_reg_pp0_iter0_empty_reg_122;
reg   [0:0] ap_phi_reg_pp0_iter1_empty_reg_122;
reg   [9:0] ap_phi_mux_storemerge_phi_fu_137_p4;
wire   [9:0] sub_ln871_fu_439_p2;
wire   [9:0] ap_phi_reg_pp0_iter1_storemerge_reg_134;
wire   [9:0] add_ln870_3_fu_452_p2;
reg   [0:0] ap_phi_mux_agg_result_0_phi_fu_148_p8;
wire   [0:0] ap_phi_reg_pp0_iter0_agg_result_0_reg_143;
reg   [0:0] ap_phi_reg_pp0_iter1_agg_result_0_reg_143;
reg   [0:0] ap_phi_reg_pp0_iter2_agg_result_0_reg_143;
reg   [7:0] ap_phi_mux_pix_val_V_1_phi_fu_167_p8;
wire   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_1_reg_162;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_val_V_1_reg_162;
reg   [7:0] ap_phi_reg_pp0_iter2_pix_val_V_1_reg_162;
reg   [7:0] ap_phi_mux_pix_val_V_2_phi_fu_184_p8;
wire   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_2_reg_181;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_val_V_2_reg_181;
reg   [7:0] ap_phi_reg_pp0_iter2_pix_val_V_2_reg_181;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln1475_fu_484_p1;
wire   [63:0] zext_ln1460_fu_508_p1;
wire   [9:0] add_ln870_fu_326_p2;
wire   [0:0] and_ln1410_fu_320_p2;
wire   [13:0] trunc_ln1397_fu_198_p1;
wire   [13:0] add_ln1397_fu_202_p2;
wire   [9:0] trunc_ln_fu_208_p4;
wire   [13:0] trunc_ln1399_fu_234_p1;
wire   [16:0] zext_ln1399_fu_230_p1;
wire   [16:0] zext_ln1405_fu_244_p1;
wire   [16:0] add_ln1405_fu_268_p2;
wire   [0:0] icmp_ln1405_2_fu_274_p2;
wire   [13:0] add_ln1399_fu_238_p2;
wire   [9:0] tmp_fu_286_p4;
wire   [10:0] zext_ln1526_fu_296_p1;
wire   [10:0] zext_ln1049_fu_310_p1;
wire   [10:0] ret_fu_300_p2;
wire   [0:0] icmp_ln1049_fu_314_p2;
wire   [16:0] zext_ln1397_fu_194_p1;
wire   [16:0] zext_ln1405_1_fu_258_p1;
wire   [16:0] sub29_fu_368_p2;
wire   [0:0] or_ln1475_fu_472_p2;
wire   [1:0] select_ln1475_1_fu_465_p3;
wire   [1:0] select_ln1475_fu_476_p3;
wire   [0:0] or_ln1460_fu_496_p2;
wire   [1:0] select_ln1460_1_fu_489_p3;
wire   [1:0] select_ln1460_fu_500_p3;
wire   [7:0] select_ln1458_fu_513_p3;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to1;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_181;
reg    ap_condition_175;
reg    ap_condition_213;
reg    ap_condition_235;
reg    ap_condition_186;
reg    ap_condition_193;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 yCount_V_2 = 10'd0;
#0 vHatch = 1'd0;
#0 xCount_V_2 = 10'd0;
end

design_1_v_tpg_0_0_tpgPatternCrossHatch_whiYuv_1 #(
    .DataWidth( 8 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
whiYuv_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(whiYuv_1_address0),
    .ce0(whiYuv_1_ce0),
    .q0(whiYuv_1_q0)
);

design_1_v_tpg_0_0_tpgPatternCrossHatch_blkYuv_1 #(
    .DataWidth( 8 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
blkYuv_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(blkYuv_1_address0),
    .ce0(blkYuv_1_ce0),
    .q0(blkYuv_1_q0)
);

design_1_v_tpg_0_0_reg_ap_uint_10_s grp_reg_ap_uint_10_s_fu_224(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .d(grp_reg_ap_uint_10_s_fu_224_d),
    .ap_return(grp_reg_ap_uint_10_s_fu_224_ap_return),
    .ap_ce(grp_reg_ap_uint_10_s_fu_224_ap_ce)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_175)) begin
        if ((1'b1 == ap_condition_181)) begin
            ap_phi_reg_pp0_iter1_empty_reg_122 <= 1'd1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_empty_reg_122 <= ap_phi_reg_pp0_iter0_empty_reg_122;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_186)) begin
        if ((1'b1 == ap_condition_235)) begin
            ap_phi_reg_pp0_iter2_agg_result_0_reg_143 <= 1'd0;
        end else if ((1'b1 == ap_condition_213)) begin
            ap_phi_reg_pp0_iter2_agg_result_0_reg_143 <= 1'd1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_agg_result_0_reg_143 <= ap_phi_reg_pp0_iter1_agg_result_0_reg_143;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_186)) begin
        if ((1'b1 == ap_condition_235)) begin
            ap_phi_reg_pp0_iter2_pix_val_V_1_reg_162 <= 8'd0;
        end else if ((1'b1 == ap_condition_213)) begin
            ap_phi_reg_pp0_iter2_pix_val_V_1_reg_162 <= 8'd255;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_pix_val_V_1_reg_162 <= ap_phi_reg_pp0_iter1_pix_val_V_1_reg_162;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_186)) begin
        if ((1'b1 == ap_condition_235)) begin
            ap_phi_reg_pp0_iter2_pix_val_V_2_reg_181 <= conv_i_fu_416_p3;
        end else if ((1'b1 == ap_condition_213)) begin
            ap_phi_reg_pp0_iter2_pix_val_V_2_reg_181 <= conv_i10_fu_409_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_pix_val_V_2_reg_181 <= ap_phi_reg_pp0_iter1_pix_val_V_2_reg_181;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_186)) begin
        if ((1'b1 == ap_condition_193)) begin
            empty_reg_122 <= vHatch;
        end else if ((1'b1 == 1'b1)) begin
            empty_reg_122 <= ap_phi_reg_pp0_iter1_empty_reg_122;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((icmp_ln1405_fu_248_p2 == 1'd0) & (1'd0 == and_ln1405_fu_280_p2) & (1'd1 == and_ln1410_fu_320_p2)) | ((icmp_ln1405_1_fu_262_p2 == 1'd0) & (icmp_ln1405_fu_248_p2 == 1'd1) & (1'd1 == and_ln1410_fu_320_p2)))) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((icmp_ln1405_fu_248_p2 == 1'd0) & (1'd1 == and_ln1405_fu_280_p2)) | ((icmp_ln1405_1_fu_262_p2 == 1'd1) & (icmp_ln1405_fu_248_p2 == 1'd1)))))) begin
        vHatch <= 1'd1;
    end else if (((icmp_ln1405_1_fu_262_p2 == 1'd1) & (icmp_ln1405_fu_248_p2 == 1'd0) & (1'd0 == and_ln1405_fu_280_p2) & (1'd0 == and_ln1410_fu_320_p2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        vHatch <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((icmp_ln1405_1_reg_549 == 1'd0) & (icmp_ln1057_fu_427_p2 == 1'd1) & (icmp_ln1429_reg_574 == 1'd0)) | ((icmp_ln1405_1_reg_549 == 1'd0) & (icmp_ln1049_1_fu_433_p2 == 1'd0) & (icmp_ln1429_reg_574 == 1'd0))))) begin
        xCount_V_2 <= ap_phi_mux_storemerge_phi_fu_137_p4;
    end else if ((((icmp_ln1405_1_fu_262_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln1405_1_reg_549 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1049_1_fu_433_p2 == 1'd1) & (icmp_ln1057_fu_427_p2 == 1'd0) & (icmp_ln1429_reg_574 == 1'd0)) | ((icmp_ln1405_1_fu_262_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1429_fu_386_p2 == 1'd1)))) begin
        xCount_V_2 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((icmp_ln1405_fu_248_p2 == 1'd0) & (1'd0 == and_ln1405_fu_280_p2) & (1'd1 == and_ln1410_fu_320_p2)) | ((icmp_ln1405_1_fu_262_p2 == 1'd0) & (icmp_ln1405_fu_248_p2 == 1'd1) & (1'd1 == and_ln1410_fu_320_p2)))) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((icmp_ln1405_fu_248_p2 == 1'd0) & (1'd1 == and_ln1405_fu_280_p2)) | ((icmp_ln1405_1_fu_262_p2 == 1'd1) & (icmp_ln1405_fu_248_p2 == 1'd1)))))) begin
        yCount_V_2 <= 10'd0;
    end else if (((icmp_ln1405_1_fu_262_p2 == 1'd1) & (icmp_ln1405_fu_248_p2 == 1'd0) & (1'd0 == and_ln1405_fu_280_p2) & (1'd0 == and_ln1410_fu_320_p2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        yCount_V_2 <= add_ln870_fu_326_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1405_fu_248_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln1405_reg_553 <= and_ln1405_fu_280_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_agg_result_0_reg_143 <= ap_phi_reg_pp0_iter0_agg_result_0_reg_143;
        ap_phi_reg_pp0_iter1_pix_val_V_1_reg_162 <= ap_phi_reg_pp0_iter0_pix_val_V_1_reg_162;
        ap_phi_reg_pp0_iter1_pix_val_V_2_reg_181 <= ap_phi_reg_pp0_iter0_pix_val_V_2_reg_181;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cmp57_reg_560 <= cmp57_fu_374_p2;
        cmp57_reg_560_pp0_iter1_reg <= cmp57_reg_560;
        cmp59_reg_566 <= cmp59_fu_380_p2;
        conv_i10_reg_578[6 : 0] <= conv_i10_fu_409_p3[6 : 0];
        conv_i_reg_584[7] <= conv_i_fu_416_p3[7];
        icmp_ln1405_1_reg_549 <= icmp_ln1405_1_fu_262_p2;
        icmp_ln1405_1_reg_549_pp0_iter1_reg <= icmp_ln1405_1_reg_549;
        icmp_ln1405_reg_539 <= icmp_ln1405_fu_248_p2;
        icmp_ln1429_reg_574_pp0_iter1_reg <= icmp_ln1429_reg_574;
        trunc_ln1405_reg_543 <= trunc_ln1405_fu_254_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1405_1_reg_549 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1057_fu_427_p2 == 1'd0) & (icmp_ln1429_reg_574 == 1'd0))) begin
        icmp_ln1049_1_reg_594 <= icmp_ln1049_1_fu_433_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1405_1_reg_549 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1429_reg_574 == 1'd0))) begin
        icmp_ln1057_reg_590 <= icmp_ln1057_fu_427_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1405_1_fu_262_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln1429_reg_574 <= icmp_ln1429_fu_386_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln1405_1_reg_549_pp0_iter1_reg == 1'd0) & (empty_reg_122 == 1'd0) & (icmp_ln1057_reg_590 == 1'd1) & (icmp_ln1429_reg_574_pp0_iter1_reg == 1'd0) & (cmp57_reg_560_pp0_iter1_reg == 1'd0)) | ((icmp_ln1405_1_reg_549_pp0_iter1_reg == 1'd0) & (empty_reg_122 == 1'd0) & (icmp_ln1049_1_reg_594 == 1'd0) & (icmp_ln1429_reg_574_pp0_iter1_reg == 1'd0) & (cmp57_reg_560_pp0_iter1_reg == 1'd0)))) begin
        ap_phi_mux_agg_result_0_phi_fu_148_p8 = 1'd0;
    end else if ((((((icmp_ln1049_1_reg_594 == 1'd1) & (icmp_ln1057_reg_590 == 1'd0) & (cmp57_reg_560_pp0_iter1_reg == 1'd0)) | ((empty_reg_122 == 1'd1) & (cmp57_reg_560_pp0_iter1_reg == 1'd0))) | ((icmp_ln1429_reg_574_pp0_iter1_reg == 1'd1) & (cmp57_reg_560_pp0_iter1_reg == 1'd0))) | ((icmp_ln1405_1_reg_549_pp0_iter1_reg == 1'd1) & (cmp57_reg_560_pp0_iter1_reg == 1'd0)))) begin
        ap_phi_mux_agg_result_0_phi_fu_148_p8 = 1'd1;
    end else begin
        ap_phi_mux_agg_result_0_phi_fu_148_p8 = ap_phi_reg_pp0_iter2_agg_result_0_reg_143;
    end
end

always @ (*) begin
    if ((((icmp_ln1405_reg_539 == 1'd0) & (1'd0 == and_ln1405_reg_553)) | ((icmp_ln1405_1_reg_549 == 1'd0) & (icmp_ln1405_reg_539 == 1'd1)))) begin
        ap_phi_mux_empty_phi_fu_126_p4 = vHatch;
    end else begin
        ap_phi_mux_empty_phi_fu_126_p4 = ap_phi_reg_pp0_iter1_empty_reg_122;
    end
end

always @ (*) begin
    if ((((icmp_ln1405_1_reg_549_pp0_iter1_reg == 1'd0) & (empty_reg_122 == 1'd0) & (icmp_ln1057_reg_590 == 1'd1) & (icmp_ln1429_reg_574_pp0_iter1_reg == 1'd0) & (cmp57_reg_560_pp0_iter1_reg == 1'd0)) | ((icmp_ln1405_1_reg_549_pp0_iter1_reg == 1'd0) & (empty_reg_122 == 1'd0) & (icmp_ln1049_1_reg_594 == 1'd0) & (icmp_ln1429_reg_574_pp0_iter1_reg == 1'd0) & (cmp57_reg_560_pp0_iter1_reg == 1'd0)))) begin
        ap_phi_mux_pix_val_V_1_phi_fu_167_p8 = blkYuv_1_q0;
    end else if ((((((icmp_ln1049_1_reg_594 == 1'd1) & (icmp_ln1057_reg_590 == 1'd0) & (cmp57_reg_560_pp0_iter1_reg == 1'd0)) | ((empty_reg_122 == 1'd1) & (cmp57_reg_560_pp0_iter1_reg == 1'd0))) | ((icmp_ln1429_reg_574_pp0_iter1_reg == 1'd1) & (cmp57_reg_560_pp0_iter1_reg == 1'd0))) | ((icmp_ln1405_1_reg_549_pp0_iter1_reg == 1'd1) & (cmp57_reg_560_pp0_iter1_reg == 1'd0)))) begin
        ap_phi_mux_pix_val_V_1_phi_fu_167_p8 = whiYuv_1_q0;
    end else begin
        ap_phi_mux_pix_val_V_1_phi_fu_167_p8 = ap_phi_reg_pp0_iter2_pix_val_V_1_reg_162;
    end
end

always @ (*) begin
    if ((((icmp_ln1405_1_reg_549_pp0_iter1_reg == 1'd0) & (empty_reg_122 == 1'd0) & (icmp_ln1057_reg_590 == 1'd1) & (icmp_ln1429_reg_574_pp0_iter1_reg == 1'd0) & (cmp57_reg_560_pp0_iter1_reg == 1'd0)) | ((icmp_ln1405_1_reg_549_pp0_iter1_reg == 1'd0) & (empty_reg_122 == 1'd0) & (icmp_ln1049_1_reg_594 == 1'd0) & (icmp_ln1429_reg_574_pp0_iter1_reg == 1'd0) & (cmp57_reg_560_pp0_iter1_reg == 1'd0)))) begin
        ap_phi_mux_pix_val_V_2_phi_fu_184_p8 = conv_i_reg_584;
    end else if ((((((icmp_ln1049_1_reg_594 == 1'd1) & (icmp_ln1057_reg_590 == 1'd0) & (cmp57_reg_560_pp0_iter1_reg == 1'd0)) | ((empty_reg_122 == 1'd1) & (cmp57_reg_560_pp0_iter1_reg == 1'd0))) | ((icmp_ln1429_reg_574_pp0_iter1_reg == 1'd1) & (cmp57_reg_560_pp0_iter1_reg == 1'd0))) | ((icmp_ln1405_1_reg_549_pp0_iter1_reg == 1'd1) & (cmp57_reg_560_pp0_iter1_reg == 1'd0)))) begin
        ap_phi_mux_pix_val_V_2_phi_fu_184_p8 = conv_i10_reg_578;
    end else begin
        ap_phi_mux_pix_val_V_2_phi_fu_184_p8 = ap_phi_reg_pp0_iter2_pix_val_V_2_reg_181;
    end
end

always @ (*) begin
    if (((icmp_ln1405_1_reg_549 == 1'd0) & (icmp_ln1429_reg_574 == 1'd0))) begin
        if ((icmp_ln1057_fu_427_p2 == 1'd1)) begin
            ap_phi_mux_storemerge_phi_fu_137_p4 = add_ln870_3_fu_452_p2;
        end else if (((icmp_ln1049_1_fu_433_p2 == 1'd0) & (icmp_ln1057_fu_427_p2 == 1'd0))) begin
            ap_phi_mux_storemerge_phi_fu_137_p4 = sub_ln871_fu_439_p2;
        end else begin
            ap_phi_mux_storemerge_phi_fu_137_p4 = ap_phi_reg_pp0_iter1_storemerge_reg_134;
        end
    end else begin
        ap_phi_mux_storemerge_phi_fu_137_p4 = ap_phi_reg_pp0_iter1_storemerge_reg_134;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to1 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        blkYuv_1_ce0 = 1'b1;
    end else begin
        blkYuv_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp14) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_reg_ap_uint_10_s_fu_224_ap_ce = 1'b1;
    end else begin
        grp_reg_ap_uint_10_s_fu_224_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        whiYuv_1_ce0 = 1'b1;
    end else begin
        whiYuv_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1397_fu_202_p2 = (trunc_ln1397_fu_198_p1 + 14'd15);

assign add_ln1399_fu_238_p2 = (trunc_ln1399_fu_234_p1 + 14'd15);

assign add_ln1405_fu_268_p2 = ($signed(zext_ln1399_fu_230_p1) + $signed(17'd131071));

assign add_ln870_3_fu_452_p2 = (xCount_V_2 + 10'd1);

assign add_ln870_fu_326_p2 = (yCount_V_2 + 10'd1);

assign and_ln1405_fu_280_p2 = (icmp_ln1405_2_fu_274_p2 & icmp_ln1405_1_fu_262_p2);

assign and_ln1410_fu_320_p2 = (icmp_ln1405_1_fu_262_p2 & icmp_ln1049_fu_314_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp14 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (1'b0 == ap_ce);
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0_ignore_call10 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call10 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call10 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_175 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_181 = (((icmp_ln1405_fu_248_p2 == 1'd0) & (1'd1 == and_ln1405_fu_280_p2)) | ((icmp_ln1405_1_fu_262_p2 == 1'd1) & (icmp_ln1405_fu_248_p2 == 1'd1)));
end

always @ (*) begin
    ap_condition_186 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_193 = (((icmp_ln1405_reg_539 == 1'd0) & (1'd0 == and_ln1405_reg_553)) | ((icmp_ln1405_1_reg_549 == 1'd0) & (icmp_ln1405_reg_539 == 1'd1)));
end

always @ (*) begin
    ap_condition_213 = (((((icmp_ln1049_1_fu_433_p2 == 1'd1) & (icmp_ln1057_fu_427_p2 == 1'd0) & (cmp57_reg_560 == 1'd1)) | ((ap_phi_mux_empty_phi_fu_126_p4 == 1'd1) & (cmp57_reg_560 == 1'd1))) | ((icmp_ln1429_reg_574 == 1'd1) & (cmp57_reg_560 == 1'd1))) | ((icmp_ln1405_1_reg_549 == 1'd1) & (cmp57_reg_560 == 1'd1)));
end

always @ (*) begin
    ap_condition_235 = (((icmp_ln1405_1_reg_549 == 1'd0) & (ap_phi_mux_empty_phi_fu_126_p4 == 1'd0) & (icmp_ln1057_fu_427_p2 == 1'd1) & (icmp_ln1429_reg_574 == 1'd0) & (cmp57_reg_560 == 1'd1)) | ((icmp_ln1405_1_reg_549 == 1'd0) & (ap_phi_mux_empty_phi_fu_126_p4 == 1'd0) & (icmp_ln1049_1_fu_433_p2 == 1'd0) & (icmp_ln1429_reg_574 == 1'd0) & (cmp57_reg_560 == 1'd1)));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_phi_reg_pp0_iter0_agg_result_0_reg_143 = 'bx;

assign ap_phi_reg_pp0_iter0_empty_reg_122 = 'bx;

assign ap_phi_reg_pp0_iter0_pix_val_V_1_reg_162 = 'bx;

assign ap_phi_reg_pp0_iter0_pix_val_V_2_reg_181 = 'bx;

assign ap_phi_reg_pp0_iter1_storemerge_reg_134 = 'bx;

assign ap_return_0 = select_ln1458_fu_513_p3;

assign ap_return_1 = ap_phi_mux_pix_val_V_1_phi_fu_167_p8;

assign ap_return_2 = ap_phi_mux_pix_val_V_2_phi_fu_184_p8;

assign blkYuv_1_address0 = zext_ln1475_fu_484_p1;

assign cmp57_fu_374_p2 = ((color == 8'd0) ? 1'b1 : 1'b0);

assign cmp59_fu_380_p2 = ((color == 8'd1) ? 1'b1 : 1'b0);

assign conv_i10_fu_409_p3 = ((cmp57_reg_560[0:0] == 1'b1) ? 8'd255 : 8'd128);

assign conv_i_fu_416_p3 = ((cmp57_reg_560[0:0] == 1'b1) ? 8'd0 : 8'd128);

assign grp_reg_ap_uint_10_s_fu_224_d = ($signed(trunc_ln_fu_208_p4) + $signed(10'd1023));

assign icmp_ln1049_1_fu_433_p2 = ((xCount_V_2 == grp_reg_ap_uint_10_s_fu_224_ap_return) ? 1'b1 : 1'b0);

assign icmp_ln1049_fu_314_p2 = ((zext_ln1049_fu_310_p1 == ret_fu_300_p2) ? 1'b1 : 1'b0);

assign icmp_ln1057_fu_427_p2 = ((xCount_V_2 < grp_reg_ap_uint_10_s_fu_224_ap_return) ? 1'b1 : 1'b0);

assign icmp_ln1405_1_fu_262_p2 = ((x == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln1405_2_fu_274_p2 = ((zext_ln1405_fu_244_p1 == add_ln1405_fu_268_p2) ? 1'b1 : 1'b0);

assign icmp_ln1405_fu_248_p2 = ((y == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln1429_fu_386_p2 = ((zext_ln1405_1_fu_258_p1 == sub29_fu_368_p2) ? 1'b1 : 1'b0);

assign or_ln1460_fu_496_p2 = (trunc_ln1405_reg_543 | cmp59_reg_566);

assign or_ln1475_fu_472_p2 = (trunc_ln1405_reg_543 | cmp59_reg_566);

assign ret_fu_300_p2 = ($signed(zext_ln1526_fu_296_p1) + $signed(11'd2047));

assign select_ln1458_fu_513_p3 = ((ap_phi_mux_agg_result_0_phi_fu_148_p8[0:0] == 1'b1) ? 8'd255 : 8'd0);

assign select_ln1460_1_fu_489_p3 = ((cmp59_reg_566[0:0] == 1'b1) ? 2'd1 : 2'd2);

assign select_ln1460_fu_500_p3 = ((or_ln1460_fu_496_p2[0:0] == 1'b1) ? select_ln1460_1_fu_489_p3 : 2'd1);

assign select_ln1475_1_fu_465_p3 = ((cmp59_reg_566[0:0] == 1'b1) ? 2'd1 : 2'd2);

assign select_ln1475_fu_476_p3 = ((or_ln1475_fu_472_p2[0:0] == 1'b1) ? select_ln1475_1_fu_465_p3 : 2'd1);

assign sub29_fu_368_p2 = ($signed(zext_ln1397_fu_194_p1) + $signed(17'd131071));

assign sub_ln871_fu_439_p2 = (xCount_V_2 - grp_reg_ap_uint_10_s_fu_224_ap_return);

assign tmp_fu_286_p4 = {{add_ln1399_fu_238_p2[13:4]}};

assign trunc_ln1397_fu_198_p1 = width[13:0];

assign trunc_ln1399_fu_234_p1 = height[13:0];

assign trunc_ln1405_fu_254_p1 = x[0:0];

assign trunc_ln_fu_208_p4 = {{add_ln1397_fu_202_p2[13:4]}};

assign whiYuv_1_address0 = zext_ln1460_fu_508_p1;

assign zext_ln1049_fu_310_p1 = yCount_V_2;

assign zext_ln1397_fu_194_p1 = width;

assign zext_ln1399_fu_230_p1 = height;

assign zext_ln1405_1_fu_258_p1 = x;

assign zext_ln1405_fu_244_p1 = y;

assign zext_ln1460_fu_508_p1 = select_ln1460_fu_500_p3;

assign zext_ln1475_fu_484_p1 = select_ln1475_fu_476_p3;

assign zext_ln1526_fu_296_p1 = tmp_fu_286_p4;

always @ (posedge ap_clk) begin
    conv_i10_reg_578[7] <= 1'b1;
    conv_i_reg_584[6:0] <= 7'b0000000;
end

endmodule //design_1_v_tpg_0_0_tpgPatternCrossHatch
