// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module design_1_v_tpg_0_0_tpgPatternCheckerBoard (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        y,
        x,
        width,
        height,
        color,
        ap_return_0,
        ap_return_1,
        ap_return_2
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [15:0] y;
input  [15:0] x;
input  [13:0] width;
input  [13:0] height;
input  [7:0] color;
output  [7:0] ap_return_0;
output  [7:0] ap_return_1;
output  [7:0] ap_return_2;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
reg   [7:0] vBarSel_2;
reg   [9:0] yCount_V_3;
reg   [2:0] hBarSel_3;
reg   [9:0] xCount_V_3;
wire   [4:0] tpgCheckerBoardArray_address0;
reg    tpgCheckerBoardArray_ce0;
wire   [1:0] tpgCheckerBoardArray_q0;
wire   [2:0] tpgBarSelRgb_r20_address0;
reg    tpgBarSelRgb_r20_ce0;
wire   [1:0] tpgBarSelRgb_r20_q0;
wire   [2:0] tpgBarSelRgb_g18_address0;
reg    tpgBarSelRgb_g18_ce0;
wire   [1:0] tpgBarSelRgb_g18_q0;
wire   [2:0] tpgBarSelRgb_b16_address0;
reg    tpgBarSelRgb_b16_ce0;
wire   [1:0] tpgBarSelRgb_b16_q0;
wire   [2:0] tpgBarSelYuv_y26_address0;
reg    tpgBarSelYuv_y26_ce0;
wire   [7:0] tpgBarSelYuv_y26_q0;
wire   [2:0] tpgBarSelYuv_v24_address0;
reg    tpgBarSelYuv_v24_ce0;
wire   [7:0] tpgBarSelYuv_v24_q0;
wire   [2:0] tpgBarSelYuv_u22_address0;
reg    tpgBarSelYuv_u22_ce0;
wire   [7:0] tpgBarSelYuv_u22_q0;
wire   [0:0] trunc_ln1507_fu_221_p1;
reg   [0:0] trunc_ln1507_reg_538;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] trunc_ln1507_reg_538_pp0_iter1_reg;
wire   [0:0] cmp46_fu_370_p2;
reg   [0:0] cmp46_reg_552;
reg   [0:0] cmp46_reg_552_pp0_iter1_reg;
wire   [0:0] cmp67_fu_376_p2;
reg   [0:0] cmp67_reg_559;
reg   [0:0] cmp67_reg_559_pp0_iter1_reg;
reg   [0:0] ap_phi_mux_vBarSel_2_loc_2_phi_fu_198_p8;
wire   [0:0] ap_phi_reg_pp0_iter0_vBarSel_2_loc_2_reg_195;
wire   [0:0] icmp_ln1519_1_fu_265_p2;
wire   [0:0] trunc_ln1519_fu_275_p1;
wire   [0:0] and_ln1524_fu_315_p2;
wire   [0:0] xor_ln1531_fu_333_p2;
wire   [0:0] icmp_ln1519_fu_253_p2;
reg   [2:0] ap_phi_mux_hBarSel_3_loc_1_phi_fu_212_p6;
wire   [2:0] ap_phi_reg_pp0_iter0_hBarSel_3_loc_1_reg_209;
wire   [0:0] icmp_ln1057_3_fu_391_p2;
wire   [2:0] add_ln1549_fu_409_p2;
wire   [63:0] zext_ln1556_fu_456_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln1556_1_fu_465_p1;
wire   [7:0] add_ln1531_fu_327_p2;
wire   [9:0] add_ln870_fu_346_p2;
wire   [9:0] sub_ln871_fu_397_p2;
wire   [9:0] add_ln870_4_fu_422_p2;
wire   [13:0] add_ln1511_fu_225_p2;
wire   [9:0] trunc_ln5_fu_231_p4;
wire   [15:0] or_ln1519_fu_259_p2;
wire   [13:0] add_ln1512_fu_247_p2;
wire   [9:0] tmp_fu_281_p4;
wire   [10:0] zext_ln1526_fu_291_p1;
wire   [10:0] zext_ln1057_fu_305_p1;
wire   [10:0] ret_fu_295_p2;
wire   [0:0] icmp_ln1057_fu_309_p2;
wire   [9:0] barWidthMinSamples_fu_241_p2;
wire   [4:0] tBarSel_fu_446_p4;
wire  signed [2:0] sext_ln1556_fu_461_p1;
wire   [0:0] and_ln1561_fu_487_p2;
wire  signed [7:0] val_assign_16_cast_fu_479_p1;
wire   [7:0] select_ln1561_fu_491_p3;
wire  signed [7:0] tpgBarSelRgb_r_load_cast_fu_475_p1;
wire  signed [7:0] tpgBarSelRgb_b_load_cast_fu_483_p1;
wire   [7:0] pix_val_V_0_fu_506_p3;
wire   [7:0] pix_val_V_1_fu_499_p3;
wire   [7:0] pix_val_V_2_fu_513_p3;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to1;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_155;
reg    ap_condition_170;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 vBarSel_2 = 8'd0;
#0 yCount_V_3 = 10'd0;
#0 hBarSel_3 = 3'd0;
#0 xCount_V_3 = 10'd0;
end

design_1_v_tpg_0_0_tpgPatternCheckerBoard_tpgCheckerBoardArray #(
    .DataWidth( 2 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
tpgCheckerBoardArray_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tpgCheckerBoardArray_address0),
    .ce0(tpgCheckerBoardArray_ce0),
    .q0(tpgCheckerBoardArray_q0)
);

design_1_v_tpg_0_0_tpgPatternDPColorSquare_DPtpgBarSelRgb_VESA_r #(
    .DataWidth( 2 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
tpgBarSelRgb_r20_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tpgBarSelRgb_r20_address0),
    .ce0(tpgBarSelRgb_r20_ce0),
    .q0(tpgBarSelRgb_r20_q0)
);

design_1_v_tpg_0_0_tpgPatternDPColorSquare_DPtpgBarSelRgb_VESA_g #(
    .DataWidth( 2 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
tpgBarSelRgb_g18_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tpgBarSelRgb_g18_address0),
    .ce0(tpgBarSelRgb_g18_ce0),
    .q0(tpgBarSelRgb_g18_q0)
);

design_1_v_tpg_0_0_tpgPatternDPColorSquare_DPtpgBarSelRgb_VESA_b #(
    .DataWidth( 2 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
tpgBarSelRgb_b16_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tpgBarSelRgb_b16_address0),
    .ce0(tpgBarSelRgb_b16_ce0),
    .q0(tpgBarSelRgb_b16_q0)
);

design_1_v_tpg_0_0_tpgPatternCheckerBoard_tpgBarSelYuv_y26 #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
tpgBarSelYuv_y26_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tpgBarSelYuv_y26_address0),
    .ce0(tpgBarSelYuv_y26_ce0),
    .q0(tpgBarSelYuv_y26_q0)
);

design_1_v_tpg_0_0_tpgPatternCheckerBoard_tpgBarSelYuv_v24 #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
tpgBarSelYuv_v24_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tpgBarSelYuv_v24_address0),
    .ce0(tpgBarSelYuv_v24_ce0),
    .q0(tpgBarSelYuv_v24_q0)
);

design_1_v_tpg_0_0_tpgPatternCheckerBoard_tpgBarSelYuv_u22 #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
tpgBarSelYuv_u22_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tpgBarSelYuv_u22_address0),
    .ce0(tpgBarSelYuv_u22_ce0),
    .q0(tpgBarSelYuv_u22_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_155)) begin
        if ((icmp_ln1519_fu_253_p2 == 1'd1)) begin
            hBarSel_3 <= 3'd0;
        end else if (((icmp_ln1057_3_fu_391_p2 == 1'd0) & (icmp_ln1519_fu_253_p2 == 1'd0))) begin
            hBarSel_3 <= add_ln1549_fu_409_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_155)) begin
        if ((icmp_ln1519_1_fu_265_p2 == 1'd1)) begin
            vBarSel_2 <= 8'd0;
        end else if ((1'b1 == ap_condition_170)) begin
            vBarSel_2 <= add_ln1531_fu_327_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_155)) begin
        if ((icmp_ln1519_fu_253_p2 == 1'd1)) begin
            xCount_V_3 <= 10'd0;
        end else if (((icmp_ln1057_3_fu_391_p2 == 1'd1) & (icmp_ln1519_fu_253_p2 == 1'd0))) begin
            xCount_V_3 <= add_ln870_4_fu_422_p2;
        end else if (((icmp_ln1057_3_fu_391_p2 == 1'd0) & (icmp_ln1519_fu_253_p2 == 1'd0))) begin
            xCount_V_3 <= sub_ln871_fu_397_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1519_1_fu_265_p2 == 1'd0) & (1'd1 == and_ln1524_fu_315_p2))) begin
        yCount_V_3 <= add_ln870_fu_346_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1519_fu_253_p2 == 1'd1) & (icmp_ln1519_1_fu_265_p2 == 1'd0) & (1'd0 == and_ln1524_fu_315_p2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1519_1_fu_265_p2 == 1'd1)))) begin
        yCount_V_3 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cmp46_reg_552 <= cmp46_fu_370_p2;
        cmp46_reg_552_pp0_iter1_reg <= cmp46_reg_552;
        cmp67_reg_559 <= cmp67_fu_376_p2;
        cmp67_reg_559_pp0_iter1_reg <= cmp67_reg_559;
        trunc_ln1507_reg_538 <= trunc_ln1507_fu_221_p1;
        trunc_ln1507_reg_538_pp0_iter1_reg <= trunc_ln1507_reg_538;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1057_3_fu_391_p2 == 1'd0) & (icmp_ln1519_fu_253_p2 == 1'd0))) begin
        ap_phi_mux_hBarSel_3_loc_1_phi_fu_212_p6 = add_ln1549_fu_409_p2;
    end else if (((icmp_ln1057_3_fu_391_p2 == 1'd1) & (icmp_ln1519_fu_253_p2 == 1'd0))) begin
        ap_phi_mux_hBarSel_3_loc_1_phi_fu_212_p6 = hBarSel_3;
    end else if ((icmp_ln1519_fu_253_p2 == 1'd1)) begin
        ap_phi_mux_hBarSel_3_loc_1_phi_fu_212_p6 = 3'd0;
    end else begin
        ap_phi_mux_hBarSel_3_loc_1_phi_fu_212_p6 = ap_phi_reg_pp0_iter0_hBarSel_3_loc_1_reg_209;
    end
end

always @ (*) begin
    if (((icmp_ln1519_fu_253_p2 == 1'd1) & (icmp_ln1519_1_fu_265_p2 == 1'd0) & (1'd0 == and_ln1524_fu_315_p2))) begin
        ap_phi_mux_vBarSel_2_loc_2_phi_fu_198_p8 = xor_ln1531_fu_333_p2;
    end else if ((((icmp_ln1519_fu_253_p2 == 1'd0) & (icmp_ln1519_1_fu_265_p2 == 1'd0) & (1'd0 == and_ln1524_fu_315_p2)) | ((icmp_ln1519_1_fu_265_p2 == 1'd0) & (1'd1 == and_ln1524_fu_315_p2)))) begin
        ap_phi_mux_vBarSel_2_loc_2_phi_fu_198_p8 = trunc_ln1519_fu_275_p1;
    end else if ((icmp_ln1519_1_fu_265_p2 == 1'd1)) begin
        ap_phi_mux_vBarSel_2_loc_2_phi_fu_198_p8 = 1'd0;
    end else begin
        ap_phi_mux_vBarSel_2_loc_2_phi_fu_198_p8 = ap_phi_reg_pp0_iter0_vBarSel_2_loc_2_reg_195;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to1 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tpgBarSelRgb_b16_ce0 = 1'b1;
    end else begin
        tpgBarSelRgb_b16_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tpgBarSelRgb_g18_ce0 = 1'b1;
    end else begin
        tpgBarSelRgb_g18_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tpgBarSelRgb_r20_ce0 = 1'b1;
    end else begin
        tpgBarSelRgb_r20_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tpgBarSelYuv_u22_ce0 = 1'b1;
    end else begin
        tpgBarSelYuv_u22_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tpgBarSelYuv_v24_ce0 = 1'b1;
    end else begin
        tpgBarSelYuv_v24_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tpgBarSelYuv_y26_ce0 = 1'b1;
    end else begin
        tpgBarSelYuv_y26_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tpgCheckerBoardArray_ce0 = 1'b1;
    end else begin
        tpgCheckerBoardArray_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1511_fu_225_p2 = (width + 14'd15);

assign add_ln1512_fu_247_p2 = (height + 14'd15);

assign add_ln1531_fu_327_p2 = (vBarSel_2 + 8'd1);

assign add_ln1549_fu_409_p2 = (hBarSel_3 + 3'd1);

assign add_ln870_4_fu_422_p2 = (xCount_V_3 + 10'd1);

assign add_ln870_fu_346_p2 = (yCount_V_3 + 10'd1);

assign and_ln1524_fu_315_p2 = (icmp_ln1519_fu_253_p2 & icmp_ln1057_fu_309_p2);

assign and_ln1561_fu_487_p2 = (trunc_ln1507_reg_538_pp0_iter1_reg & cmp67_reg_559_pp0_iter1_reg);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (1'b0 == ap_ce);
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_155 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_170 = ((icmp_ln1519_fu_253_p2 == 1'd1) & (icmp_ln1519_1_fu_265_p2 == 1'd0) & (1'd0 == and_ln1524_fu_315_p2));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_phi_reg_pp0_iter0_hBarSel_3_loc_1_reg_209 = 'bx;

assign ap_phi_reg_pp0_iter0_vBarSel_2_loc_2_reg_195 = 'bx;

assign ap_return_0 = pix_val_V_0_fu_506_p3;

assign ap_return_1 = pix_val_V_1_fu_499_p3;

assign ap_return_2 = pix_val_V_2_fu_513_p3;

assign barWidthMinSamples_fu_241_p2 = ($signed(trunc_ln5_fu_231_p4) + $signed(10'd1023));

assign cmp46_fu_370_p2 = ((color == 8'd0) ? 1'b1 : 1'b0);

assign cmp67_fu_376_p2 = ((color != 8'd1) ? 1'b1 : 1'b0);

assign icmp_ln1057_3_fu_391_p2 = ((xCount_V_3 < barWidthMinSamples_fu_241_p2) ? 1'b1 : 1'b0);

assign icmp_ln1057_fu_309_p2 = (($signed(zext_ln1057_fu_305_p1) < $signed(ret_fu_295_p2)) ? 1'b1 : 1'b0);

assign icmp_ln1519_1_fu_265_p2 = ((or_ln1519_fu_259_p2 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln1519_fu_253_p2 = ((x == 16'd0) ? 1'b1 : 1'b0);

assign or_ln1519_fu_259_p2 = (y | x);

assign pix_val_V_0_fu_506_p3 = ((cmp46_reg_552_pp0_iter1_reg[0:0] == 1'b1) ? tpgBarSelRgb_r_load_cast_fu_475_p1 : tpgBarSelYuv_y26_q0);

assign pix_val_V_1_fu_499_p3 = ((cmp46_reg_552_pp0_iter1_reg[0:0] == 1'b1) ? val_assign_16_cast_fu_479_p1 : select_ln1561_fu_491_p3);

assign pix_val_V_2_fu_513_p3 = ((cmp46_reg_552_pp0_iter1_reg[0:0] == 1'b1) ? tpgBarSelRgb_b_load_cast_fu_483_p1 : tpgBarSelYuv_v24_q0);

assign ret_fu_295_p2 = ($signed(zext_ln1526_fu_291_p1) + $signed(11'd2047));

assign select_ln1561_fu_491_p3 = ((and_ln1561_fu_487_p2[0:0] == 1'b1) ? tpgBarSelYuv_v24_q0 : tpgBarSelYuv_u22_q0);

assign sext_ln1556_fu_461_p1 = $signed(tpgCheckerBoardArray_q0);

assign sub_ln871_fu_397_p2 = (xCount_V_3 - barWidthMinSamples_fu_241_p2);

assign tBarSel_fu_446_p4 = {{{ap_phi_mux_vBarSel_2_loc_2_phi_fu_198_p8}, {1'd0}}, {ap_phi_mux_hBarSel_3_loc_1_phi_fu_212_p6}};

assign tmp_fu_281_p4 = {{add_ln1512_fu_247_p2[13:4]}};

assign tpgBarSelRgb_b16_address0 = zext_ln1556_1_fu_465_p1;

assign tpgBarSelRgb_b_load_cast_fu_483_p1 = $signed(tpgBarSelRgb_b16_q0);

assign tpgBarSelRgb_g18_address0 = zext_ln1556_1_fu_465_p1;

assign tpgBarSelRgb_r20_address0 = zext_ln1556_1_fu_465_p1;

assign tpgBarSelRgb_r_load_cast_fu_475_p1 = $signed(tpgBarSelRgb_r20_q0);

assign tpgBarSelYuv_u22_address0 = zext_ln1556_1_fu_465_p1;

assign tpgBarSelYuv_v24_address0 = zext_ln1556_1_fu_465_p1;

assign tpgBarSelYuv_y26_address0 = zext_ln1556_1_fu_465_p1;

assign tpgCheckerBoardArray_address0 = zext_ln1556_fu_456_p1;

assign trunc_ln1507_fu_221_p1 = x[0:0];

assign trunc_ln1519_fu_275_p1 = vBarSel_2[0:0];

assign trunc_ln5_fu_231_p4 = {{add_ln1511_fu_225_p2[13:4]}};

assign val_assign_16_cast_fu_479_p1 = $signed(tpgBarSelRgb_g18_q0);

assign xor_ln1531_fu_333_p2 = (trunc_ln1519_fu_275_p1 ^ 1'd1);

assign zext_ln1057_fu_305_p1 = yCount_V_3;

assign zext_ln1526_fu_291_p1 = tmp_fu_281_p4;

assign zext_ln1556_1_fu_465_p1 = $unsigned(sext_ln1556_fu_461_p1);

assign zext_ln1556_fu_456_p1 = tBarSel_fu_446_p4;

endmodule //design_1_v_tpg_0_0_tpgPatternCheckerBoard
