// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module design_1_v_tpg_0_0_tpgPatternDPColorSquare (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        y,
        x,
        color,
        dpDynamicRange,
        dpYUVCoef,
        ap_return_0,
        ap_return_1,
        ap_return_2
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [15:0] y;
input  [15:0] x;
input  [7:0] color;
input  [7:0] dpDynamicRange;
input  [7:0] dpYUVCoef;
output  [7:0] ap_return_0;
output  [7:0] ap_return_1;
output  [7:0] ap_return_2;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
reg   [0:0] vBarSel_1;
reg   [5:0] yCount_V_1;
reg   [2:0] hBarSel_1;
reg   [9:0] xCount_V_1;
wire   [3:0] DPtpgBarArray_address0;
reg    DPtpgBarArray_ce0;
wire   [2:0] DPtpgBarArray_q0;
wire   [2:0] DPtpgBarSelRgb_VESA_r_address0;
reg    DPtpgBarSelRgb_VESA_r_ce0;
wire   [1:0] DPtpgBarSelRgb_VESA_r_q0;
wire   [2:0] DPtpgBarSelRgb_VESA_g_address0;
reg    DPtpgBarSelRgb_VESA_g_ce0;
wire   [1:0] DPtpgBarSelRgb_VESA_g_q0;
wire   [2:0] DPtpgBarSelRgb_VESA_b_address0;
reg    DPtpgBarSelRgb_VESA_b_ce0;
wire   [1:0] DPtpgBarSelRgb_VESA_b_q0;
wire   [2:0] DPtpgBarSelRgb_CEA_r_address0;
reg    DPtpgBarSelRgb_CEA_r_ce0;
wire   [5:0] DPtpgBarSelRgb_CEA_r_q0;
wire   [2:0] DPtpgBarSelRgb_CEA_g_address0;
reg    DPtpgBarSelRgb_CEA_g_ce0;
wire   [5:0] DPtpgBarSelRgb_CEA_g_q0;
wire   [2:0] DPtpgBarSelRgb_CEA_b_address0;
reg    DPtpgBarSelRgb_CEA_b_ce0;
wire   [5:0] DPtpgBarSelRgb_CEA_b_q0;
wire   [2:0] DPtpgBarSelYuv_601_y_address0;
reg    DPtpgBarSelYuv_601_y_ce0;
wire   [7:0] DPtpgBarSelYuv_601_y_q0;
wire   [2:0] DPtpgBarSelYuv_601_v_address0;
reg    DPtpgBarSelYuv_601_v_ce0;
wire   [7:0] DPtpgBarSelYuv_601_v_q0;
wire   [2:0] DPtpgBarSelYuv_709_y_address0;
reg    DPtpgBarSelYuv_709_y_ce0;
wire   [7:0] DPtpgBarSelYuv_709_y_q0;
wire   [2:0] DPtpgBarSelYuv_709_v_address0;
reg    DPtpgBarSelYuv_709_v_ce0;
wire   [7:0] DPtpgBarSelYuv_709_v_q0;
wire   [2:0] DPtpgBarSelYuv_601_u_address0;
reg    DPtpgBarSelYuv_601_u_ce0;
wire   [7:0] DPtpgBarSelYuv_601_u_q0;
wire   [2:0] DPtpgBarSelYuv_709_u_address0;
reg    DPtpgBarSelYuv_709_u_ce0;
wire   [7:0] DPtpgBarSelYuv_709_u_q0;
wire   [0:0] cmp41_fu_394_p2;
reg   [0:0] cmp41_reg_780;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] cmp41_reg_780_pp0_iter1_reg;
wire   [0:0] cmp106_fu_400_p2;
reg   [0:0] cmp106_reg_787;
reg   [0:0] cmp106_reg_787_pp0_iter1_reg;
wire   [0:0] and_ln1759_fu_509_p2;
reg   [0:0] and_ln1759_reg_801;
reg   [0:0] and_ln1759_reg_801_pp0_iter1_reg;
wire   [0:0] empty_65_fu_521_p2;
reg   [0:0] empty_65_reg_808;
reg   [0:0] empty_65_reg_808_pp0_iter1_reg;
wire   [0:0] sel_tmp2_fu_527_p2;
reg   [0:0] sel_tmp2_reg_815;
reg   [0:0] sel_tmp2_reg_815_pp0_iter1_reg;
reg   [0:0] ap_phi_mux_vBarSel_3_loc_2_phi_fu_284_p8;
wire   [0:0] ap_phi_reg_pp0_iter0_vBarSel_3_loc_2_reg_281;
wire   [0:0] icmp_ln1704_1_fu_323_p2;
wire   [0:0] and_ln1709_fu_345_p2;
wire   [0:0] xor_ln1716_fu_357_p2;
wire   [0:0] icmp_ln1704_fu_311_p2;
reg   [2:0] ap_phi_mux_hBarSel_5_loc_1_phi_fu_298_p6;
wire   [2:0] ap_phi_reg_pp0_iter0_hBarSel_5_loc_1_reg_295;
wire   [0:0] icmp_ln1057_2_fu_419_p2;
wire   [2:0] add_ln1733_fu_437_p2;
wire   [63:0] zext_ln1742_fu_498_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln1742_1_fu_533_p1;
wire   [5:0] add_ln870_fu_370_p2;
wire   [9:0] add_ln871_fu_425_p2;
wire   [9:0] zext_ln870_fu_456_p1;
wire   [15:0] or_ln1704_fu_317_p2;
wire   [0:0] icmp_ln1057_fu_339_p2;
wire   [5:0] trunc_ln1057_fu_415_p1;
wire   [5:0] add_ln870_2_fu_450_p2;
wire   [3:0] or_ln_fu_478_p3;
wire   [7:0] zext_ln1736_fu_486_p1;
wire   [10:0] tmp_2_fu_490_p3;
wire   [0:0] trunc_ln1704_fu_307_p1;
wire   [0:0] icmp_ln1759_fu_503_p2;
wire   [7:0] empty_fu_515_p2;
wire   [0:0] sel_tmp5_fu_577_p2;
wire   [0:0] sel_tmp6_fu_582_p2;
wire   [0:0] xor_ln1759_fu_592_p2;
wire   [0:0] sel_tmp16_demorgan_fu_603_p2;
wire   [0:0] sel_tmp16_fu_607_p2;
wire   [0:0] and_ln1759_3_fu_613_p2;
wire   [0:0] and_ln1759_2_fu_597_p2;
wire   [0:0] and_ln1759_1_fu_587_p2;
wire  signed [7:0] val_assign_8_cast_fu_565_p1;
wire   [0:0] sel_tmp3_fu_573_p2;
wire  signed [7:0] val_assign_5_cast_fu_553_p1;
wire   [0:0] or_ln1759_fu_626_p2;
wire   [7:0] select_ln1759_fu_618_p3;
wire   [7:0] select_ln1759_1_fu_632_p3;
wire   [0:0] or_ln1759_1_fu_640_p2;
wire   [0:0] or_ln1759_2_fu_661_p2;
wire   [7:0] select_ln1759_3_fu_653_p3;
wire   [7:0] select_ln1759_2_fu_646_p3;
wire  signed [7:0] trunc_ln314_2_cast_fu_561_p1;
wire  signed [7:0] sext_ln314_fu_549_p1;
wire   [7:0] select_ln1759_5_fu_675_p3;
wire   [7:0] select_ln1759_6_fu_683_p3;
wire   [7:0] select_ln1759_8_fu_698_p3;
wire   [7:0] select_ln1759_7_fu_691_p3;
wire  signed [7:0] val_assign_9_cast_fu_569_p1;
wire  signed [7:0] val_assign_6_cast_fu_557_p1;
wire   [7:0] select_ln1759_10_fu_714_p3;
wire   [7:0] select_ln1759_11_fu_722_p3;
wire   [7:0] select_ln1759_13_fu_737_p3;
wire   [7:0] select_ln1759_12_fu_730_p3;
wire   [7:0] select_ln1759_9_fu_706_p3;
wire   [7:0] select_ln1759_4_fu_667_p3;
wire   [7:0] select_ln1759_14_fu_745_p3;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to1;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_217;
reg    ap_condition_232;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 vBarSel_1 = 1'd0;
#0 yCount_V_1 = 6'd0;
#0 hBarSel_1 = 3'd0;
#0 xCount_V_1 = 10'd0;
end

design_1_v_tpg_0_0_tpgPatternDPColorSquare_DPtpgBarArray #(
    .DataWidth( 3 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
DPtpgBarArray_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(DPtpgBarArray_address0),
    .ce0(DPtpgBarArray_ce0),
    .q0(DPtpgBarArray_q0)
);

design_1_v_tpg_0_0_tpgPatternDPColorSquare_DPtpgBarSelRgb_VESA_r #(
    .DataWidth( 2 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
DPtpgBarSelRgb_VESA_r_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(DPtpgBarSelRgb_VESA_r_address0),
    .ce0(DPtpgBarSelRgb_VESA_r_ce0),
    .q0(DPtpgBarSelRgb_VESA_r_q0)
);

design_1_v_tpg_0_0_tpgPatternDPColorSquare_DPtpgBarSelRgb_VESA_g #(
    .DataWidth( 2 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
DPtpgBarSelRgb_VESA_g_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(DPtpgBarSelRgb_VESA_g_address0),
    .ce0(DPtpgBarSelRgb_VESA_g_ce0),
    .q0(DPtpgBarSelRgb_VESA_g_q0)
);

design_1_v_tpg_0_0_tpgPatternDPColorSquare_DPtpgBarSelRgb_VESA_b #(
    .DataWidth( 2 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
DPtpgBarSelRgb_VESA_b_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(DPtpgBarSelRgb_VESA_b_address0),
    .ce0(DPtpgBarSelRgb_VESA_b_ce0),
    .q0(DPtpgBarSelRgb_VESA_b_q0)
);

design_1_v_tpg_0_0_tpgPatternDPColorSquare_DPtpgBarSelRgb_CEA_r #(
    .DataWidth( 6 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
DPtpgBarSelRgb_CEA_r_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(DPtpgBarSelRgb_CEA_r_address0),
    .ce0(DPtpgBarSelRgb_CEA_r_ce0),
    .q0(DPtpgBarSelRgb_CEA_r_q0)
);

design_1_v_tpg_0_0_tpgPatternDPColorSquare_DPtpgBarSelRgb_CEA_g #(
    .DataWidth( 6 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
DPtpgBarSelRgb_CEA_g_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(DPtpgBarSelRgb_CEA_g_address0),
    .ce0(DPtpgBarSelRgb_CEA_g_ce0),
    .q0(DPtpgBarSelRgb_CEA_g_q0)
);

design_1_v_tpg_0_0_tpgPatternDPColorSquare_DPtpgBarSelRgb_CEA_b #(
    .DataWidth( 6 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
DPtpgBarSelRgb_CEA_b_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(DPtpgBarSelRgb_CEA_b_address0),
    .ce0(DPtpgBarSelRgb_CEA_b_ce0),
    .q0(DPtpgBarSelRgb_CEA_b_q0)
);

design_1_v_tpg_0_0_tpgPatternDPColorSquare_DPtpgBarSelYuv_601_y #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
DPtpgBarSelYuv_601_y_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(DPtpgBarSelYuv_601_y_address0),
    .ce0(DPtpgBarSelYuv_601_y_ce0),
    .q0(DPtpgBarSelYuv_601_y_q0)
);

design_1_v_tpg_0_0_tpgPatternDPColorSquare_DPtpgBarSelYuv_601_v #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
DPtpgBarSelYuv_601_v_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(DPtpgBarSelYuv_601_v_address0),
    .ce0(DPtpgBarSelYuv_601_v_ce0),
    .q0(DPtpgBarSelYuv_601_v_q0)
);

design_1_v_tpg_0_0_tpgPatternDPColorSquare_DPtpgBarSelYuv_709_y #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
DPtpgBarSelYuv_709_y_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(DPtpgBarSelYuv_709_y_address0),
    .ce0(DPtpgBarSelYuv_709_y_ce0),
    .q0(DPtpgBarSelYuv_709_y_q0)
);

design_1_v_tpg_0_0_tpgPatternDPColorSquare_DPtpgBarSelYuv_709_v #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
DPtpgBarSelYuv_709_v_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(DPtpgBarSelYuv_709_v_address0),
    .ce0(DPtpgBarSelYuv_709_v_ce0),
    .q0(DPtpgBarSelYuv_709_v_q0)
);

design_1_v_tpg_0_0_tpgPatternDPColorSquare_DPtpgBarSelYuv_601_u #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
DPtpgBarSelYuv_601_u_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(DPtpgBarSelYuv_601_u_address0),
    .ce0(DPtpgBarSelYuv_601_u_ce0),
    .q0(DPtpgBarSelYuv_601_u_q0)
);

design_1_v_tpg_0_0_tpgPatternDPColorSquare_DPtpgBarSelYuv_709_u #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
DPtpgBarSelYuv_709_u_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(DPtpgBarSelYuv_709_u_address0),
    .ce0(DPtpgBarSelYuv_709_u_ce0),
    .q0(DPtpgBarSelYuv_709_u_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_217)) begin
        if ((icmp_ln1704_fu_311_p2 == 1'd1)) begin
            hBarSel_1 <= 3'd0;
        end else if (((icmp_ln1057_2_fu_419_p2 == 1'd0) & (icmp_ln1704_fu_311_p2 == 1'd0))) begin
            hBarSel_1 <= add_ln1733_fu_437_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_217)) begin
        if ((icmp_ln1704_1_fu_323_p2 == 1'd1)) begin
            vBarSel_1 <= 1'd0;
        end else if ((1'b1 == ap_condition_232)) begin
            vBarSel_1 <= xor_ln1716_fu_357_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_217)) begin
        if ((icmp_ln1704_fu_311_p2 == 1'd1)) begin
            xCount_V_1 <= 10'd0;
        end else if (((icmp_ln1057_2_fu_419_p2 == 1'd1) & (icmp_ln1704_fu_311_p2 == 1'd0))) begin
            xCount_V_1 <= zext_ln870_fu_456_p1;
        end else if (((icmp_ln1057_2_fu_419_p2 == 1'd0) & (icmp_ln1704_fu_311_p2 == 1'd0))) begin
            xCount_V_1 <= add_ln871_fu_425_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1704_1_fu_323_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'd1 == and_ln1709_fu_345_p2))) begin
        yCount_V_1 <= add_ln870_fu_370_p2;
    end else if ((((1'd0 == and_ln1709_fu_345_p2) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1704_fu_311_p2 == 1'd1) & (icmp_ln1704_1_fu_323_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1704_1_fu_323_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        yCount_V_1 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln1759_reg_801 <= and_ln1759_fu_509_p2;
        and_ln1759_reg_801_pp0_iter1_reg <= and_ln1759_reg_801;
        cmp106_reg_787 <= cmp106_fu_400_p2;
        cmp106_reg_787_pp0_iter1_reg <= cmp106_reg_787;
        cmp41_reg_780 <= cmp41_fu_394_p2;
        cmp41_reg_780_pp0_iter1_reg <= cmp41_reg_780;
        empty_65_reg_808 <= empty_65_fu_521_p2;
        empty_65_reg_808_pp0_iter1_reg <= empty_65_reg_808;
        sel_tmp2_reg_815 <= sel_tmp2_fu_527_p2;
        sel_tmp2_reg_815_pp0_iter1_reg <= sel_tmp2_reg_815;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        DPtpgBarArray_ce0 = 1'b1;
    end else begin
        DPtpgBarArray_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        DPtpgBarSelRgb_CEA_b_ce0 = 1'b1;
    end else begin
        DPtpgBarSelRgb_CEA_b_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        DPtpgBarSelRgb_CEA_g_ce0 = 1'b1;
    end else begin
        DPtpgBarSelRgb_CEA_g_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        DPtpgBarSelRgb_CEA_r_ce0 = 1'b1;
    end else begin
        DPtpgBarSelRgb_CEA_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        DPtpgBarSelRgb_VESA_b_ce0 = 1'b1;
    end else begin
        DPtpgBarSelRgb_VESA_b_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        DPtpgBarSelRgb_VESA_g_ce0 = 1'b1;
    end else begin
        DPtpgBarSelRgb_VESA_g_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        DPtpgBarSelRgb_VESA_r_ce0 = 1'b1;
    end else begin
        DPtpgBarSelRgb_VESA_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        DPtpgBarSelYuv_601_u_ce0 = 1'b1;
    end else begin
        DPtpgBarSelYuv_601_u_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        DPtpgBarSelYuv_601_v_ce0 = 1'b1;
    end else begin
        DPtpgBarSelYuv_601_v_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        DPtpgBarSelYuv_601_y_ce0 = 1'b1;
    end else begin
        DPtpgBarSelYuv_601_y_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        DPtpgBarSelYuv_709_u_ce0 = 1'b1;
    end else begin
        DPtpgBarSelYuv_709_u_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        DPtpgBarSelYuv_709_v_ce0 = 1'b1;
    end else begin
        DPtpgBarSelYuv_709_v_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        DPtpgBarSelYuv_709_y_ce0 = 1'b1;
    end else begin
        DPtpgBarSelYuv_709_y_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1057_2_fu_419_p2 == 1'd0) & (icmp_ln1704_fu_311_p2 == 1'd0))) begin
        ap_phi_mux_hBarSel_5_loc_1_phi_fu_298_p6 = add_ln1733_fu_437_p2;
    end else if (((icmp_ln1057_2_fu_419_p2 == 1'd1) & (icmp_ln1704_fu_311_p2 == 1'd0))) begin
        ap_phi_mux_hBarSel_5_loc_1_phi_fu_298_p6 = hBarSel_1;
    end else if ((icmp_ln1704_fu_311_p2 == 1'd1)) begin
        ap_phi_mux_hBarSel_5_loc_1_phi_fu_298_p6 = 3'd0;
    end else begin
        ap_phi_mux_hBarSel_5_loc_1_phi_fu_298_p6 = ap_phi_reg_pp0_iter0_hBarSel_5_loc_1_reg_295;
    end
end

always @ (*) begin
    if (((1'd0 == and_ln1709_fu_345_p2) & (icmp_ln1704_fu_311_p2 == 1'd1) & (icmp_ln1704_1_fu_323_p2 == 1'd0))) begin
        ap_phi_mux_vBarSel_3_loc_2_phi_fu_284_p8 = xor_ln1716_fu_357_p2;
    end else if ((((1'd0 == and_ln1709_fu_345_p2) & (icmp_ln1704_fu_311_p2 == 1'd0) & (icmp_ln1704_1_fu_323_p2 == 1'd0)) | ((icmp_ln1704_1_fu_323_p2 == 1'd0) & (1'd1 == and_ln1709_fu_345_p2)))) begin
        ap_phi_mux_vBarSel_3_loc_2_phi_fu_284_p8 = vBarSel_1;
    end else if ((icmp_ln1704_1_fu_323_p2 == 1'd1)) begin
        ap_phi_mux_vBarSel_3_loc_2_phi_fu_284_p8 = 1'd0;
    end else begin
        ap_phi_mux_vBarSel_3_loc_2_phi_fu_284_p8 = ap_phi_reg_pp0_iter0_vBarSel_3_loc_2_reg_281;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to1 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign DPtpgBarArray_address0 = zext_ln1742_fu_498_p1;

assign DPtpgBarSelRgb_CEA_b_address0 = zext_ln1742_1_fu_533_p1;

assign DPtpgBarSelRgb_CEA_g_address0 = zext_ln1742_1_fu_533_p1;

assign DPtpgBarSelRgb_CEA_r_address0 = zext_ln1742_1_fu_533_p1;

assign DPtpgBarSelRgb_VESA_b_address0 = zext_ln1742_1_fu_533_p1;

assign DPtpgBarSelRgb_VESA_g_address0 = zext_ln1742_1_fu_533_p1;

assign DPtpgBarSelRgb_VESA_r_address0 = zext_ln1742_1_fu_533_p1;

assign DPtpgBarSelYuv_601_u_address0 = zext_ln1742_1_fu_533_p1;

assign DPtpgBarSelYuv_601_v_address0 = zext_ln1742_1_fu_533_p1;

assign DPtpgBarSelYuv_601_y_address0 = zext_ln1742_1_fu_533_p1;

assign DPtpgBarSelYuv_709_u_address0 = zext_ln1742_1_fu_533_p1;

assign DPtpgBarSelYuv_709_v_address0 = zext_ln1742_1_fu_533_p1;

assign DPtpgBarSelYuv_709_y_address0 = zext_ln1742_1_fu_533_p1;

assign add_ln1733_fu_437_p2 = (hBarSel_1 + 3'd1);

assign add_ln870_2_fu_450_p2 = (trunc_ln1057_fu_415_p1 + 6'd1);

assign add_ln870_fu_370_p2 = (yCount_V_1 + 6'd1);

assign add_ln871_fu_425_p2 = ($signed(xCount_V_1) + $signed(10'd961));

assign and_ln1709_fu_345_p2 = (icmp_ln1704_fu_311_p2 & icmp_ln1057_fu_339_p2);

assign and_ln1759_1_fu_587_p2 = (sel_tmp6_fu_582_p2 & and_ln1759_reg_801_pp0_iter1_reg);

assign and_ln1759_2_fu_597_p2 = (xor_ln1759_fu_592_p2 & sel_tmp6_fu_582_p2);

assign and_ln1759_3_fu_613_p2 = (sel_tmp16_fu_607_p2 & and_ln1759_reg_801_pp0_iter1_reg);

assign and_ln1759_fu_509_p2 = (trunc_ln1704_fu_307_p1 & icmp_ln1759_fu_503_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (1'b0 == ap_ce);
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_217 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_232 = ((1'd0 == and_ln1709_fu_345_p2) & (icmp_ln1704_fu_311_p2 == 1'd1) & (icmp_ln1704_1_fu_323_p2 == 1'd0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_phi_reg_pp0_iter0_hBarSel_5_loc_1_reg_295 = 'bx;

assign ap_phi_reg_pp0_iter0_vBarSel_3_loc_2_reg_281 = 'bx;

assign ap_return_0 = select_ln1759_9_fu_706_p3;

assign ap_return_1 = select_ln1759_4_fu_667_p3;

assign ap_return_2 = select_ln1759_14_fu_745_p3;

assign cmp106_fu_400_p2 = ((dpYUVCoef == 8'd0) ? 1'b1 : 1'b0);

assign cmp41_fu_394_p2 = ((color == 8'd0) ? 1'b1 : 1'b0);

assign empty_65_fu_521_p2 = ((empty_fu_515_p2 == 8'd0) ? 1'b1 : 1'b0);

assign empty_fu_515_p2 = (dpDynamicRange | color);

assign icmp_ln1057_2_fu_419_p2 = ((xCount_V_1 < 10'd63) ? 1'b1 : 1'b0);

assign icmp_ln1057_fu_339_p2 = ((yCount_V_1 != 6'd63) ? 1'b1 : 1'b0);

assign icmp_ln1704_1_fu_323_p2 = ((or_ln1704_fu_317_p2 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln1704_fu_311_p2 = ((x == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln1759_fu_503_p2 = ((color != 8'd1) ? 1'b1 : 1'b0);

assign or_ln1704_fu_317_p2 = (y | x);

assign or_ln1759_1_fu_640_p2 = (sel_tmp3_fu_573_p2 | and_ln1759_1_fu_587_p2);

assign or_ln1759_2_fu_661_p2 = (or_ln1759_fu_626_p2 | or_ln1759_1_fu_640_p2);

assign or_ln1759_fu_626_p2 = (and_ln1759_3_fu_613_p2 | and_ln1759_2_fu_597_p2);

assign or_ln_fu_478_p3 = {{ap_phi_mux_vBarSel_3_loc_2_phi_fu_284_p8}, {ap_phi_mux_hBarSel_5_loc_1_phi_fu_298_p6}};

assign sel_tmp16_demorgan_fu_603_p2 = (cmp41_reg_780_pp0_iter1_reg | cmp106_reg_787_pp0_iter1_reg);

assign sel_tmp16_fu_607_p2 = (sel_tmp16_demorgan_fu_603_p2 ^ 1'd1);

assign sel_tmp2_fu_527_p2 = ((dpDynamicRange != 8'd0) ? 1'b1 : 1'b0);

assign sel_tmp3_fu_573_p2 = (sel_tmp2_reg_815_pp0_iter1_reg & cmp41_reg_780_pp0_iter1_reg);

assign sel_tmp5_fu_577_p2 = (cmp41_reg_780_pp0_iter1_reg ^ 1'd1);

assign sel_tmp6_fu_582_p2 = (sel_tmp5_fu_577_p2 & cmp106_reg_787_pp0_iter1_reg);

assign select_ln1759_10_fu_714_p3 = ((and_ln1759_3_fu_613_p2[0:0] == 1'b1) ? DPtpgBarSelYuv_709_v_q0 : DPtpgBarSelYuv_601_v_q0);

assign select_ln1759_11_fu_722_p3 = ((and_ln1759_1_fu_587_p2[0:0] == 1'b1) ? DPtpgBarSelYuv_601_v_q0 : val_assign_9_cast_fu_569_p1);

assign select_ln1759_12_fu_730_p3 = ((empty_65_reg_808_pp0_iter1_reg[0:0] == 1'b1) ? val_assign_6_cast_fu_557_p1 : DPtpgBarSelYuv_709_v_q0);

assign select_ln1759_13_fu_737_p3 = ((or_ln1759_fu_626_p2[0:0] == 1'b1) ? select_ln1759_10_fu_714_p3 : select_ln1759_11_fu_722_p3);

assign select_ln1759_14_fu_745_p3 = ((or_ln1759_2_fu_661_p2[0:0] == 1'b1) ? select_ln1759_13_fu_737_p3 : select_ln1759_12_fu_730_p3);

assign select_ln1759_1_fu_632_p3 = ((and_ln1759_1_fu_587_p2[0:0] == 1'b1) ? DPtpgBarSelYuv_601_v_q0 : val_assign_8_cast_fu_565_p1);

assign select_ln1759_2_fu_646_p3 = ((empty_65_reg_808_pp0_iter1_reg[0:0] == 1'b1) ? val_assign_5_cast_fu_553_p1 : DPtpgBarSelYuv_709_u_q0);

assign select_ln1759_3_fu_653_p3 = ((or_ln1759_fu_626_p2[0:0] == 1'b1) ? select_ln1759_fu_618_p3 : select_ln1759_1_fu_632_p3);

assign select_ln1759_4_fu_667_p3 = ((or_ln1759_2_fu_661_p2[0:0] == 1'b1) ? select_ln1759_3_fu_653_p3 : select_ln1759_2_fu_646_p3);

assign select_ln1759_5_fu_675_p3 = ((and_ln1759_3_fu_613_p2[0:0] == 1'b1) ? DPtpgBarSelYuv_709_y_q0 : DPtpgBarSelYuv_601_y_q0);

assign select_ln1759_6_fu_683_p3 = ((and_ln1759_1_fu_587_p2[0:0] == 1'b1) ? DPtpgBarSelYuv_601_y_q0 : trunc_ln314_2_cast_fu_561_p1);

assign select_ln1759_7_fu_691_p3 = ((empty_65_reg_808_pp0_iter1_reg[0:0] == 1'b1) ? sext_ln314_fu_549_p1 : DPtpgBarSelYuv_709_y_q0);

assign select_ln1759_8_fu_698_p3 = ((or_ln1759_fu_626_p2[0:0] == 1'b1) ? select_ln1759_5_fu_675_p3 : select_ln1759_6_fu_683_p3);

assign select_ln1759_9_fu_706_p3 = ((or_ln1759_2_fu_661_p2[0:0] == 1'b1) ? select_ln1759_8_fu_698_p3 : select_ln1759_7_fu_691_p3);

assign select_ln1759_fu_618_p3 = ((and_ln1759_3_fu_613_p2[0:0] == 1'b1) ? DPtpgBarSelYuv_709_v_q0 : DPtpgBarSelYuv_601_u_q0);

assign sext_ln314_fu_549_p1 = $signed(DPtpgBarSelRgb_VESA_r_q0);

assign tmp_2_fu_490_p3 = {{3'd0}, {zext_ln1736_fu_486_p1}};

assign trunc_ln1057_fu_415_p1 = xCount_V_1[5:0];

assign trunc_ln1704_fu_307_p1 = x[0:0];

assign trunc_ln314_2_cast_fu_561_p1 = $signed(DPtpgBarSelRgb_CEA_r_q0);

assign val_assign_5_cast_fu_553_p1 = $signed(DPtpgBarSelRgb_VESA_g_q0);

assign val_assign_6_cast_fu_557_p1 = $signed(DPtpgBarSelRgb_VESA_b_q0);

assign val_assign_8_cast_fu_565_p1 = $signed(DPtpgBarSelRgb_CEA_g_q0);

assign val_assign_9_cast_fu_569_p1 = $signed(DPtpgBarSelRgb_CEA_b_q0);

assign xor_ln1716_fu_357_p2 = (vBarSel_1 ^ 1'd1);

assign xor_ln1759_fu_592_p2 = (1'd1 ^ and_ln1759_reg_801_pp0_iter1_reg);

assign zext_ln1736_fu_486_p1 = or_ln_fu_478_p3;

assign zext_ln1742_1_fu_533_p1 = DPtpgBarArray_q0;

assign zext_ln1742_fu_498_p1 = tmp_2_fu_490_p3;

assign zext_ln870_fu_456_p1 = add_ln870_2_fu_450_p2;

endmodule //design_1_v_tpg_0_0_tpgPatternDPColorSquare
